### ISSUE TITLE
http://host:port/ke 错误

### ISSUE THREAD

**Issue by zhixingchou** [smartloli/Kafka-Eagle-Wiki#1]
配置了Zookeeper 集群地址，第一次启动有数据，显示消费者有误；我测试环境有2个消费者，只显示未启动的消费者；
由于测试环境网络故障，重启kafka-eagle后，url 界面没有显示监控信息。

**Comment by smartloli** [comment]
问题可以在群里咨询，在 Git 上不一定能及时解答。
